site_name: HQDM Implementation Patterns
copyright: Copyright &copy; 2023 Critical Insight Security Ltd

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ClimbingAl/HqdmPatterns

extra_css:
  - stylesheets/extra.css

plugins:
  - glightbox
  - search
  - table-reader

theme:
  name: material
  palette:
    - scheme: default
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    - scheme: slate
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.code.copy
  icon:
    annotation: material/plus-circle
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

markdown_extensions:
  - abbr
  - attr_list
  - def_list
  - md_in_html
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: ["docs/extras/example-files"]
  - pymdownx.superfences
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - 'index.md'
  - 'scenario.md'
  - 'Introducing HQDM':
    - introducing_hqdm/basic_intro_to_hqdm.md
    - introducing_hqdm/top_level_type.md
    - introducing_hqdm/diagrams_used.md
  - 'Fundamental Relations':
    - fundamental_elements/relations.md
    - fundamental_elements/parts.md
    - fundamental_elements/sets.md
    - fundamental_elements/order.md
  - 'Individual':
    - individual/individual.md
    - individual/individual_LM5.md
    - individual/individual_queries.md
  - 'Activity and Association':
    - 'Association' :
      - association/association.md
      - association/associationEagleCrew.md
    - 'Activity' :
      - activity/activity.md
      - activity/activityEagle.md
  - 'Sign and Pattern':
    - signs_and_patterns/what_are_signs.md
    - signs_and_patterns/sign.md
    - signs_and_patterns/sign_options_by_diagram.md
    - signs_and_patterns/patterns.md
    - signs_and_patterns/sign_and_pattern.md
    - signs_and_patterns/sign_and_pattern_apollo_example.md
  - 'System and System Component':
    - system/system.md
    - system/system_component.md
    - system/system_LM5.md
    - system/system_spatio-temporal-extents.md
  - 'Properties and Qualities':
    - properties/properties.md
  - 'Levels of Reality':
    - levels_of_reality/multiple_inheritance.md
    - levels_of_reality/types_of_states.md
  - 'Implementation Guidance':
    - implementation_guidance/managing_immutable_data.md
    - implementation_guidance/model_mapping_process.md
    - implementation_guidance/lifecycle_activity_models_to_support_information_requirements.md

