``` mermaid
graph LR
  05700d38-1db0-48d8-9e81-80e558ac666f(("patterns <br> 05700d38-1db0-48d8 <br> -9e81-80e558ac666f"))--->|"data_EntityName"|Example_individual_that_is_Lunar_Module_Eagle_LM-5["Example_individual <br> _that_is_Lunar_Module_Eagle_LM-5"];
  05700d38-1db0-48d8-9e81-80e558ac666f(("patterns <br> 05700d38-1db0-48d8 <br> -9e81-80e558ac666f"))--->|"type"|physical_object(["hqdm <br> physical_object"]);
  cda5b2ce-ccb2-42d8-9425-8495b562f8ff(("patterns <br> cda5b2ce-ccb2-42d8 <br> -9425-8495b562f8ff"))--->|"<b> temporal_part_of"|05700d38-1db0-48d8-9e81-80e558ac666f(("patterns <br> 05700d38-1db0-48d8 <br> -9e81-80e558ac666f"));
  cda5b2ce-ccb2-42d8-9425-8495b562f8ff(("patterns <br> cda5b2ce-ccb2-42d8 <br> -9425-8495b562f8ff"))--->|"data_EntityName"|Example_state_of_Lunar_Module_Eagle_LM-5["Example_state_of <br> _Lunar_Module_Eagle_LM-5"];
  cda5b2ce-ccb2-42d8-9425-8495b562f8ff(("patterns <br> cda5b2ce-ccb2-42d8 <br> -9425-8495b562f8ff"))--->|"type"|individual(["hqdm <br> individual"]);
```
