``` mermaid
graph TD
  thing(thing)-->|supertype_of|Class(Class);
  thing(thing)-->|supertype_of|spatio_temporal_extent(spatio_temporal <br> _extent);
  style thing stroke-width:6px;
  style Class stroke-width:2px;
  style spatio_temporal_extent stroke-width:2px;
```
