``` mermaid
graph TD
  abstract_object-->|supertype_of|Class;
  thing-->|supertype_of|spatio_temporal_extent;
  class_of_state-->|supertype_of|class_of_individual;
  Class-->|supertype_of|class_of_spatio_temporal_extent;
  state-->|supertype_of|individual;
  spatio_temporal_extent-->|supertype_of|state;
  class_of_individual-->|supertype_of|kind_of_individual;
  class_of_state_of_physical_object-->|supertype_of|class_of_physical_object;
  class_of_individual-->|supertype_of|class_of_physical_object;
  class_of_spatio_temporal_extent-->|supertype_of|class_of_state;
  state_of_physical_object-->|supertype_of|physical_object;
  individual-->|supertype_of|physical_object;
  state-->|supertype_of|state_of_physical_object;
  kind_of_individual-->|supertype_of|kind_of_physical_object;
  class_of_physical_object-->|supertype_of|kind_of_physical_object;
  class_of_state-->|supertype_of|class_of_state_of_physical_object;
  style physical_object stroke-width:4px;
  style state_of_physical_object stroke-width:4px;
  style kind_of_physical_object stroke-width:4px;
  style class_of_state_of_physical_object stroke-width:4px;
  thing-->|supertype_of|abstract_object;
```
