``` mermaid
graph LR
  835bff4a-4f6f-4987-8d54-f57415c7dd2b(("patterns <br> 835bff4a-4f6f-4987 <br> -8d54-f57415c7dd2b"))--->|"<b> member_of"|79ef0ad4-727e-42d3-ae02-0e883047b873(("<b> patterns-rdl <br> 79ef0ad4-727e-42d3 <br> -ae02-0e883047b873"));
  835bff4a-4f6f-4987-8d54-f57415c7dd2b(("patterns <br> 835bff4a-4f6f-4987 <br> -8d54-f57415c7dd2b"))--->|"data_EntityName"|Example_state_of_Lunar_Lander_Module_Eagle_LM-5["Example_state_of <br> _Lunar_Lander_Module_Eagle_LM-5"];
  835bff4a-4f6f-4987-8d54-f57415c7dd2b(("patterns <br> 835bff4a-4f6f-4987 <br> -8d54-f57415c7dd2b"))--->|"type"|state_of_functional_object(["hqdm <br> state_of_functiona <br> l_object"]);
  79ef0ad4-727e-42d3-ae02-0e883047b873(("<b> patterns-rdl <br> 79ef0ad4-727e-42d3 <br> -ae02-0e883047b873"))--->|"data_EntityName"|ClassOfStateOfFunctionalObject__State_Of_Lunar_Lander["ClassOfStateOfFunctionalObject <br> __State_Of_Lunar_Lander"];
  79ef0ad4-727e-42d3-ae02-0e883047b873(("<b> patterns-rdl <br> 79ef0ad4-727e-42d3 <br> -ae02-0e883047b873"))--->|"part__of_by_class"|734fd694-3ae1-434c-9b69-246baea5f6e8(("patterns-rdl <br> 734fd694-3ae1-434c <br> -9b69-246baea5f6e8"));
  79ef0ad4-727e-42d3-ae02-0e883047b873(("<b> patterns-rdl <br> 79ef0ad4-727e-42d3 <br> -ae02-0e883047b873"))--->|"type"|class_of_state_of_functional_object(["hqdm <br> class_of_state_of_ <br> functional_object"]);
```
