``` mermaid
graph LR
  3c24e63f-ceff-4f3c-ade5-f84bd9a8ed04(("patterns <br> 3c24e63f-ceff-4f3c <br> -ade5-f84bd9a8ed04"))--->|"<b> member_of"|31a1fa4b-9733-4b44-81e4-f13e69a87e20(("<b> patterns-rdl <br> 31a1fa4b-9733-4b44 <br> -81e4-f13e69a87e20"));
  3c24e63f-ceff-4f3c-ade5-f84bd9a8ed04(("patterns <br> 3c24e63f-ceff-4f3c <br> -ade5-f84bd9a8ed04"))--->|"data_EntityName"|Example_state_of_Lunar_Module_Eagle_LM-5["Example_state_of <br> _Lunar_Module_Eagle_LM-5"];
  3c24e63f-ceff-4f3c-ade5-f84bd9a8ed04(("patterns <br> 3c24e63f-ceff-4f3c <br> -ade5-f84bd9a8ed04"))--->|"type"|individual(["hqdm <br> individual"]);
  31a1fa4b-9733-4b44-81e4-f13e69a87e20(("<b> patterns-rdl <br> 31a1fa4b-9733-4b44 <br> -81e4-f13e69a87e20"))--->|"data_EntityName"|ClassOfStateOfPhysicalObject__State_Of_Lunar_Lander["ClassOfStateOfPhysicalObject <br> __State_Of_Lunar_Lander"];
  31a1fa4b-9733-4b44-81e4-f13e69a87e20(("<b> patterns-rdl <br> 31a1fa4b-9733-4b44 <br> -81e4-f13e69a87e20"))--->|"type"|class_of_state_of_physical_object(["hqdm <br> class_of_state_of_ <br> physical_object"]);
```
