``` mermaid
graph LR
  bfade502-ecef-4272-90b2-34100b6ed58a(("patterns <br> bfade502-ecef-4272 <br> -90b2-34100b6ed58a"))--->|"<b> member_of_kind"|4cfee906-b8ef-4d42-861e-5d1cf5d1febb(("patterns-rdl <br> 4cfee906-b8ef-4d42 <br> -861e-5d1cf5d1febb"));
  bfade502-ecef-4272-90b2-34100b6ed58a(("patterns <br> bfade502-ecef-4272 <br> -90b2-34100b6ed58a"))--->|"data_EntityName"|Example_individual_that_is_Lunar_Module_Eagle_LM-5["Example_individual <br> _that_is_Lunar_Module_Eagle_LM-5"];
  bfade502-ecef-4272-90b2-34100b6ed58a(("patterns <br> bfade502-ecef-4272 <br> -90b2-34100b6ed58a"))--->|"type"|functional_object(["hqdm <br> functional_object"]);
  4cfee906-b8ef-4d42-861e-5d1cf5d1febb(("patterns-rdl <br> 4cfee906-b8ef-4d42 <br> -861e-5d1cf5d1febb"))--->|"data_EntityName"|KindOfFunctionalObject__Lunar_Lander["KindOfFunctionalObject <br> __Lunar_Lander"];
  4cfee906-b8ef-4d42-861e-5d1cf5d1febb(("patterns-rdl <br> 4cfee906-b8ef-4d42 <br> -861e-5d1cf5d1febb"))--->|"type"|kind_of_functional_object(["hqdm <br> kind_of_functional <br> _object"]);
```
