``` mermaid
graph LR
  f6c644ed-c19d-4c99-a6fa-33b8d7d663fb(("patterns <br> f6c644ed-c19d-4c99 <br> -a6fa-33b8d7d663fb"))--->|"<b> member_of_kind"|dbc1dc89-7d87-4ecf-ad2a-ff3ecb32c7bc(("patterns-rdl <br> dbc1dc89-7d87-4ecf <br> -ad2a-ff3ecb32c7bc"));
  f6c644ed-c19d-4c99-a6fa-33b8d7d663fb(("patterns <br> f6c644ed-c19d-4c99 <br> -a6fa-33b8d7d663fb"))--->|"data_EntityName"|Example_individual_that_is_Lunar_Module_Eagle_LM-5["Example_individual <br> _that_is_Lunar_Module_Eagle_LM-5"];
  f6c644ed-c19d-4c99-a6fa-33b8d7d663fb(("patterns <br> f6c644ed-c19d-4c99 <br> -a6fa-33b8d7d663fb"))--->|"type"|physical_object(["hqdm <br> physical_object"]);
  dbc1dc89-7d87-4ecf-ad2a-ff3ecb32c7bc(("patterns-rdl <br> dbc1dc89-7d87-4ecf <br> -ad2a-ff3ecb32c7bc"))--->|"data_EntityName"|KindOfPhysicalObject__Lunar_Lander["KindOfPhysicalObject <br> __Lunar_Lander"];
  dbc1dc89-7d87-4ecf-ad2a-ff3ecb32c7bc(("patterns-rdl <br> dbc1dc89-7d87-4ecf <br> -ad2a-ff3ecb32c7bc"))--->|"type"|kind_of_physical_object(["hqdm <br> kind_of_physical_o <br> bject"]);
```
