``` mermaid
graph LR
  3c24e63f-ceff-4f3c-ade5-f84bd9a8ed04(("patterns <br> 3c24e63f-ceff-4f3c <br> -ade5-f84bd9a8ed04"))--->|"<b> temporal_part_of"|f6c644ed-c19d-4c99-a6fa-33b8d7d663fb(("patterns <br> f6c644ed-c19d-4c99 <br> -a6fa-33b8d7d663fb"));
```
