``` mermaid
graph LR
  f6c644ed-c19d-4c99-a6fa-33b8d7d663fb(("patterns <br> f6c644ed-c19d-4c99 <br> -a6fa-33b8d7d663fb"))--->|"<b> part_of_possible_world"|83f61dc0-1a2f-4780-bf5e-7e06fea690b1(("patterns <br> 83f61dc0-1a2f-4780 <br> -bf5e-7e06fea690b1"));
  f6c644ed-c19d-4c99-a6fa-33b8d7d663fb(("patterns <br> f6c644ed-c19d-4c99 <br> -a6fa-33b8d7d663fb"))--->|"data_EntityName"|Example_individual_that_is_Lunar_Module_Eagle_LM-5["Example_individual <br> _that_is_Lunar_Module_Eagle_LM-5"];
  f6c644ed-c19d-4c99-a6fa-33b8d7d663fb(("patterns <br> f6c644ed-c19d-4c99 <br> -a6fa-33b8d7d663fb"))--->|"type"|physical_object(["hqdm <br> physical_object"]);
  3c24e63f-ceff-4f3c-ade5-f84bd9a8ed04(("patterns <br> 3c24e63f-ceff-4f3c <br> -ade5-f84bd9a8ed04"))--->|"<b> part_of_possible_world"|83f61dc0-1a2f-4780-bf5e-7e06fea690b1(("patterns <br> 83f61dc0-1a2f-4780 <br> -bf5e-7e06fea690b1"));
  3c24e63f-ceff-4f3c-ade5-f84bd9a8ed04(("patterns <br> 3c24e63f-ceff-4f3c <br> -ade5-f84bd9a8ed04"))--->|"<b> temporal_part_of"|f6c644ed-c19d-4c99-a6fa-33b8d7d663fb(("patterns <br> f6c644ed-c19d-4c99 <br> -a6fa-33b8d7d663fb"));
  3c24e63f-ceff-4f3c-ade5-f84bd9a8ed04(("patterns <br> 3c24e63f-ceff-4f3c <br> -ade5-f84bd9a8ed04"))--->|"data_EntityName"|Example_state_of_Lunar_Module_Eagle_LM-5["Example_state_of <br> _Lunar_Module_Eagle_LM-5"];
  3c24e63f-ceff-4f3c-ade5-f84bd9a8ed04(("patterns <br> 3c24e63f-ceff-4f3c <br> -ade5-f84bd9a8ed04"))--->|"type"|individual(["hqdm <br> individual"]);
```
