``` mermaid
graph LR
  06cff4dc-17fe-47e6-aacf-790ce7932037(("patterns <br> 06cff4dc-17fe-47e6 <br> -aacf-790ce7932037"))--->|"data_EntityName"|Example_individual_that_is_Lunar_Module_Eagle_LM-5["Example_individual <br> _that_is_Lunar_Module_Eagle_LM-5"];
  06cff4dc-17fe-47e6-aacf-790ce7932037(("patterns <br> 06cff4dc-17fe-47e6 <br> -aacf-790ce7932037"))--->|"type"|functional_object(["hqdm <br> functional_object"]);
  bf0718b8-b671-4d54-8658-04548cc6e04c(("patterns <br> bf0718b8-b671-4d54 <br> -8658-04548cc6e04c"))--->|"<b> temporal_part_of"|06cff4dc-17fe-47e6-aacf-790ce7932037(("patterns <br> 06cff4dc-17fe-47e6 <br> -aacf-790ce7932037"));
  bf0718b8-b671-4d54-8658-04548cc6e04c(("patterns <br> bf0718b8-b671-4d54 <br> -8658-04548cc6e04c"))--->|"data_EntityName"|Example_state_of_Lunar_Lander_Module_Eagle_LM-5["Example_state_of <br> _Lunar_Lander_Module_Eagle_LM-5"];
  bf0718b8-b671-4d54-8658-04548cc6e04c(("patterns <br> bf0718b8-b671-4d54 <br> -8658-04548cc6e04c"))--->|"type"|state_of_functional_object(["hqdm <br> state_of_functiona <br> l_object"]);
```
