``` mermaid
graph LR
  a5a6ba71-b2bb-4ed5-b079-e7cab5dac94f(("<b> patterns <br> a5a6ba71-b2bb-4ed5 <br> -b079-e7cab5dac94f"))--->|"member_of_kind"|e7f02ac1-d9bd-4d5a-b961-442fcfdcd93c(("patterns-rdl <br> e7f02ac1-d9bd-4d5a <br> -b961-442fcfdcd93c"));
  a5a6ba71-b2bb-4ed5-b079-e7cab5dac94f(("<b> patterns <br> a5a6ba71-b2bb-4ed5 <br> -b079-e7cab5dac94f"))--->|"part_of_possible_world"|bb4dcf61-3ea6-48fa-820e-4eb739ae6671(("patterns <br> bb4dcf61-3ea6-48fa <br> -820e-4eb739ae6671"));
  a5a6ba71-b2bb-4ed5-b079-e7cab5dac94f(("<b> patterns <br> a5a6ba71-b2bb-4ed5 <br> -b079-e7cab5dac94f"))--->|"data_EntityName"|Example_individual_that_is_Lunar_Module_Eagle_LM-5["Example_individual <br> _that_is_Lunar_Module_Eagle_LM-5"];
  a5a6ba71-b2bb-4ed5-b079-e7cab5dac94f(("<b> patterns <br> a5a6ba71-b2bb-4ed5 <br> -b079-e7cab5dac94f"))--->|"ending"|3a3962dd-59f5-4a60-b8c7-d57509b1314f(("patterns <br> 3a3962dd-59f5-4a60 <br> -b8c7-d57509b1314f"));
  a5a6ba71-b2bb-4ed5-b079-e7cab5dac94f(("<b> patterns <br> a5a6ba71-b2bb-4ed5 <br> -b079-e7cab5dac94f"))--->|"type"|functional_system(["hqdm <br> functional_system"]);
  e7f02ac1-d9bd-4d5a-b961-442fcfdcd93c(("patterns-rdl <br> e7f02ac1-d9bd-4d5a <br> -b961-442fcfdcd93c"))--->|"data_EntityName"|KindOfFunctionalSystem__Lunar_Lander["KindOfFunctionalSystem <br> __Lunar_Lander"];
  e7f02ac1-d9bd-4d5a-b961-442fcfdcd93c(("patterns-rdl <br> e7f02ac1-d9bd-4d5a <br> -b961-442fcfdcd93c"))--->|"type"|kind_of_functional_system(["hqdm <br> kind_of_functional <br> _system"]);
```
