``` mermaid
graph LR
  6d2e977b-3ae2-4abf-8071-85de1593dfab(("patterns <br> 6d2e977b-3ae2-4abf <br> -8071-85de1593dfab"))--->|"<b> member_of"|dd206fa1-6575-4e29-b0ff-b8299cc7a085(("<b> patterns-rdl <br> dd206fa1-6575-4e29 <br> -b0ff-b8299cc7a085"));
  6d2e977b-3ae2-4abf-8071-85de1593dfab(("patterns <br> 6d2e977b-3ae2-4abf <br> -8071-85de1593dfab"))--->|"data_EntityName"|Example_state_of_Lunar_Lander_Module_Eagle_LM-5["Example_state_of <br> _Lunar_Lander_Module_Eagle_LM-5"];
  6d2e977b-3ae2-4abf-8071-85de1593dfab(("patterns <br> 6d2e977b-3ae2-4abf <br> -8071-85de1593dfab"))--->|"type"|state_of_functional_system(["hqdm <br> state_of_functiona <br> l_system"]);
  dd206fa1-6575-4e29-b0ff-b8299cc7a085(("<b> patterns-rdl <br> dd206fa1-6575-4e29 <br> -b0ff-b8299cc7a085"))--->|"data_EntityName"|ClassOfStateOfFunctionalSystem__State_Of_Lunar_Lander["ClassOfStateOfFunctionalSystem <br> __State_Of_Lunar_Lander"];
  dd206fa1-6575-4e29-b0ff-b8299cc7a085(("<b> patterns-rdl <br> dd206fa1-6575-4e29 <br> -b0ff-b8299cc7a085"))--->|"part__of_by_class"|ee4b236b-2982-41a1-ab73-2e2444324e15(("patterns-rdl <br> ee4b236b-2982-41a1 <br> -ab73-2e2444324e15"));
  dd206fa1-6575-4e29-b0ff-b8299cc7a085(("<b> patterns-rdl <br> dd206fa1-6575-4e29 <br> -b0ff-b8299cc7a085"))--->|"type"|class_of_state_of_functional_system(["hqdm <br> class_of_state_of_ <br> functional_system"]);
```
