``` mermaid
graph LR
  e7b2866d-7667-4e3c-b829-1a23ae21f1c1(("patterns <br> e7b2866d-7667-4e3c <br> -b829-1a23ae21f1c1"))--->|"<b> member_of"|e42236eb-5602-4897-a2e3-a373944e3de9(("<b> patterns-rdl <br> e42236eb-5602-4897 <br> -a2e3-a373944e3de9"));
  e7b2866d-7667-4e3c-b829-1a23ae21f1c1(("patterns <br> e7b2866d-7667-4e3c <br> -b829-1a23ae21f1c1"))--->|"data_EntityName"|Example_state_of_Lunar_Lander_Module_Eagle_LM-5["Example_state_of <br> _Lunar_Lander_Module_Eagle_LM-5"];
  e7b2866d-7667-4e3c-b829-1a23ae21f1c1(("patterns <br> e7b2866d-7667-4e3c <br> -b829-1a23ae21f1c1"))--->|"type"|state_of_functional_system(["hqdm <br> state_of_functiona <br> l_system"]);
  e42236eb-5602-4897-a2e3-a373944e3de9(("<b> patterns-rdl <br> e42236eb-5602-4897 <br> -a2e3-a373944e3de9"))--->|"data_EntityName"|ClassOfStateOfFunctionalSystem__State_Of_Lunar_Lander["ClassOfStateOfFunctionalSystem <br> __State_Of_Lunar_Lander"];
  e42236eb-5602-4897-a2e3-a373944e3de9(("<b> patterns-rdl <br> e42236eb-5602-4897 <br> -a2e3-a373944e3de9"))--->|"part__of_by_class"|e7f02ac1-d9bd-4d5a-b961-442fcfdcd93c(("patterns-rdl <br> e7f02ac1-d9bd-4d5a <br> -b961-442fcfdcd93c"));
  e42236eb-5602-4897-a2e3-a373944e3de9(("<b> patterns-rdl <br> e42236eb-5602-4897 <br> -a2e3-a373944e3de9"))--->|"type"|class_of_state_of_functional_system(["hqdm <br> class_of_state_of_ <br> functional_system"]);
```
