``` mermaid
graph TD
  state_of_physical_object(state_of_physical <br> _object)-->|supertype_of|state_of_ordinary_physical_object(state_of_ordinary <br> _physical_object);
  abstract_object(abstract_object)-->|supertype_of|Class(Class);
  class_of_state_of_physical_object(class_of_state_of <br> _physical_object)-->|supertype_of|class_of_state_of_ordinary_physical_object(class_of_state_of <br> _ordinary_physical_object);
  class_of_state_of_physical_object(class_of_state_of <br> _physical_object)-->|supertype_of|class_of_physical_object(class_of_physical <br> _object);
  class_of_individual(class_of_individual)-->|supertype_of|class_of_physical_object(class_of_physical <br> _object);
  thing(thing)-->|supertype_of|spatio_temporal_extent(spatio_temporal <br> _extent);
  state_of_ordinary_physical_object(state_of_ordinary <br> _physical_object)-->|supertype_of|state_of_system(state_of_system);
  Class(Class)-->|supertype_of|class_of_spatio_temporal_extent(class_of_spatio <br> _temporal_extent);
  class_of_state_of_ordinary_physical_object(class_of_state_of <br> _ordinary_physical_object)-->|supertype_of|class_of_state_of_system(class_of_state_of <br> _system);
  class_of_state_of_ordinary_physical_object(class_of_state_of <br> _ordinary_physical_object)-->|supertype_of|class_of_ordinary_physical_object(class_of_ordinary <br> _physical_object);
  class_of_physical_object(class_of_physical <br> _object)-->|supertype_of|class_of_ordinary_physical_object(class_of_ordinary <br> _physical_object);
  kind_of_individual(kind_of_individual)-->|supertype_of|kind_of_physical_object(kind_of_physical <br> _object);
  class_of_physical_object(class_of_physical <br> _object)-->|supertype_of|kind_of_physical_object(kind_of_physical <br> _object);
  state(state)-->|supertype_of|state_of_intentionally_constructed_object(state_of_intentionally <br> _constructed_object);
  spatio_temporal_extent(spatio_temporal <br> _extent)-->|supertype_of|state(state);
  state_of_system(state_of_system)-->|supertype_of|state_of_party(state_of_party);
  class_of_spatio_temporal_extent(class_of_spatio <br> _temporal_extent)-->|supertype_of|class_of_state(class_of_state);
  class_of_state(class_of_state)-->|supertype_of|class_of_state_of_intentionally_constructed_object(class_of_state_of <br> _intentionally_constructed_object);
  class_of_state_of_system(class_of_state_of <br> _system)-->|supertype_of|class_of_state_of_party(class_of_state_of <br> _party);
  class_of_ordinary_physical_object(class_of_ordinary <br> _physical_object)-->|supertype_of|class_of_system(class_of_system);
  class_of_state_of_system(class_of_state_of <br> _system)-->|supertype_of|class_of_system(class_of_system);
  class_of_ordinary_physical_object(class_of_ordinary <br> _physical_object)-->|supertype_of|kind_of_ordinary_physical_object(kind_of_ordinary <br> _physical_object);
  kind_of_physical_object(kind_of_physical <br> _object)-->|supertype_of|kind_of_ordinary_physical_object(kind_of_ordinary <br> _physical_object);
  class_of_individual(class_of_individual)-->|supertype_of|kind_of_individual(kind_of_individual);
  state_of_intentionally_constructed_object(state_of_intentionally <br> _constructed_object)-->|supertype_of|state_of_socially_constructed_object(state_of_socially <br> _constructed_object);
  individual(individual)-->|supertype_of|intentionally_constructed_object(intentionally_constructed <br> _object);
  state_of_intentionally_constructed_object(state_of_intentionally <br> _constructed_object)-->|supertype_of|intentionally_constructed_object(intentionally_constructed <br> _object);
  state(state)-->|supertype_of|state_of_physical_object(state_of_physical <br> _object);
  state(state)-->|supertype_of|state_of_association(state_of_association);
  state(state)-->|supertype_of|individual(individual);
  state_of_socially_constructed_object(state_of_socially <br> _constructed_object)-->|supertype_of|state_of_organization(state_of_organi <br> zation);
  state_of_party(state_of_party)-->|supertype_of|state_of_organization(state_of_organi <br> zation);
  class_of_state(class_of_state)-->|supertype_of|class_of_state_of_association(class_of_state_of <br> _association);
  class_of_state(class_of_state)-->|supertype_of|class_of_individual(class_of_individual);
  class_of_individual(class_of_individual)-->|supertype_of|class_of_intentionally_constructed_object(class_of_intentionally <br> _constructed_object);
  class_of_state_of_intentionally_constructed_object(class_of_state_of <br> _intentionally_constructed_object)-->|supertype_of|class_of_intentionally_constructed_object(class_of_intentionally <br> _constructed_object);
  class_of_state_of_intentionally_constructed_object(class_of_state_of <br> _intentionally_constructed_object)-->|supertype_of|class_of_state_of_socially_constructed_object(class_of_state_of <br> _socially_constructed_object);
  class_of_state_of_party(class_of_state_of <br> _party)-->|supertype_of|class_of_party(class_of_party);
  class_of_system(class_of_system)-->|supertype_of|class_of_party(class_of_party);
  kind_of_ordinary_physical_object(kind_of_ordinary <br> _physical_object)-->|supertype_of|kind_of_system(kind_of_system);
  class_of_system(class_of_system)-->|supertype_of|kind_of_system(kind_of_system);
  class_of_state_of_socially_constructed_object(class_of_state_of <br> _socially_constructed_object)-->|supertype_of|class_of_state_of_organization(class_of_state_of <br> _organization);
  class_of_state_of_party(class_of_state_of <br> _party)-->|supertype_of|class_of_state_of_organization(class_of_state_of <br> _organization);
  class_of_intentionally_constructed_object(class_of_intentionally <br> _constructed_object)-->|supertype_of|kind_of_intentionally_constructed_object(kind_of_intentionally <br> _constructed_object);
  kind_of_individual(kind_of_individual)-->|supertype_of|kind_of_intentionally_constructed_object(kind_of_intentionally <br> _constructed_object);
  class_of_state(class_of_state)-->|supertype_of|class_of_state_of_physical_object(class_of_state_of <br> _physical_object);
  state_of_socially_constructed_object(state_of_socially <br> _constructed_object)-->|supertype_of|socially_constructed_object(socially_constructed <br> _object);
  intentionally_constructed_object(intentionally_constructed <br> _object)-->|supertype_of|socially_constructed_object(socially_constructed <br> _object);
  state_of_physical_object(state_of_physical <br> _object)-->|supertype_of|participant(participant);
  state_of_socially_constructed_object(state_of_socially <br> _constructed_object)-->|supertype_of|state_of_sign(state_of_sign);
  state_of_association(state_of_association)-->|supertype_of|association(association);
  individual(individual)-->|supertype_of|association(association);
  state_of_organization(state_of_organi <br> zation)-->|supertype_of|state_of_language_community(state_of_language <br> _community);
  class_of_state_of_association(class_of_state_of <br> _association)-->|supertype_of|class_of_association(class_of_association);
  class_of_individual(class_of_individual)-->|supertype_of|class_of_association(class_of_association);
  class_of_intentionally_constructed_object(class_of_intentionally <br> _constructed_object)-->|supertype_of|class_of_socially_constructed_object(class_of_socially <br> _constructed_object);
  class_of_state_of_socially_constructed_object(class_of_state_of <br> _socially_constructed_object)-->|supertype_of|class_of_socially_constructed_object(class_of_socially <br> _constructed_object);
  class_of_state_of_socially_constructed_object(class_of_state_of <br> _socially_constructed_object)-->|supertype_of|class_of_state_of_sign(class_of_state_of <br> _sign);
  class_of_party(class_of_party)-->|supertype_of|kind_of_party(kind_of_party);
  kind_of_system(kind_of_system)-->|supertype_of|kind_of_party(kind_of_party);
  class_of_party(class_of_party)-->|supertype_of|class_of_organization(class_of_organi <br> zation);
  class_of_socially_constructed_object(class_of_socially <br> _constructed_object)-->|supertype_of|class_of_organization(class_of_organi <br> zation);
  class_of_state_of_organization(class_of_state_of <br> _organization)-->|supertype_of|class_of_organization(class_of_organi <br> zation);
  class_of_socially_constructed_object(class_of_socially <br> _constructed_object)-->|supertype_of|kind_of_socially_constructed_object(kind_of_socially <br> _constructed_object);
  kind_of_intentionally_constructed_object(kind_of_intentionally <br> _constructed_object)-->|supertype_of|kind_of_socially_constructed_object(kind_of_socially <br> _constructed_object);
  class_of_state_of_physical_object(class_of_state_of <br> _physical_object)-->|supertype_of|class_of_participant(class_of_participant);
  socially_constructed_object(socially_constructed <br> _object)-->|supertype_of|sign(sign);
  participant(participant)-->|supertype_of|sign(sign);
  state_of_sign(state_of_sign)-->|supertype_of|sign(sign);
  association(association)-->|supertype_of|representation_by_sign(representation_by <br> _sign);
  participant(participant)-->|supertype_of|recognizing_language_community(recognizing_language <br> _community);
  state_of_language_community(state_of_language <br> _community)-->|supertype_of|recognizing_language_community(recognizing_language <br> _community);
  class_of_association(class_of_association)-->|supertype_of|class_of_representation(class_of_repres <br> entation);
  class_of_socially_constructed_object(class_of_socially <br> _constructed_object)-->|supertype_of|class_of_sign(class_of_sign);
  class_of_state_of_sign(class_of_state_of <br> _sign)-->|supertype_of|class_of_sign(class_of_sign);
  kind_of_party(kind_of_party)-->|supertype_of|kind_of_organization(kind_of_organization);
  class_of_organization(class_of_organi <br> zation)-->|supertype_of|kind_of_organization(kind_of_organization);
  kind_of_socially_constructed_object(kind_of_socially <br> _constructed_object)-->|supertype_of|kind_of_organization(kind_of_organization);
  class_of_participant(class_of_participant)-->|supertype_of|role(role);
  style sign stroke-width:4px;
  style representation_by_sign stroke-width:4px;
  style recognizing_language_community stroke-width:4px;
  style class_of_representation stroke-width:4px;
  style class_of_sign stroke-width:4px;
  style kind_of_organization stroke-width:4px;
  style role stroke-width:4px;
  thing-->|supertype_of|abstract_object;
```
