``` mermaid
graph LR
  2af35b4d-4c62-4d7d-942d-7c0f527f9a2c(("patterns <br> 2af35b4d-4c62-4d7d <br> -942d-7c0f527f9a2c"))--->|"<b> part_of_possible_world"|56c160dd-0304-442f-90c8-e5e647bd65fe(("patterns <br> 56c160dd-0304-442f <br> -90c8-e5e647bd65fe"));
  2af35b4d-4c62-4d7d-942d-7c0f527f9a2c(("patterns <br> 2af35b4d-4c62-4d7d <br> -942d-7c0f527f9a2c"))--->|"data_EntityName"|Example_individual_that_is_Lunar_Module_Eagle_LM-5["Example_individual <br> _that_is_Lunar_Module_Eagle_LM-5"];
  2af35b4d-4c62-4d7d-942d-7c0f527f9a2c(("patterns <br> 2af35b4d-4c62-4d7d <br> -942d-7c0f527f9a2c"))--->|"type"|functional_system(["hqdm <br> functional_system"]);
  6d2e977b-3ae2-4abf-8071-85de1593dfab(("patterns <br> 6d2e977b-3ae2-4abf <br> -8071-85de1593dfab"))--->|"<b> part_of_possible_world"|56c160dd-0304-442f-90c8-e5e647bd65fe(("patterns <br> 56c160dd-0304-442f <br> -90c8-e5e647bd65fe"));
  6d2e977b-3ae2-4abf-8071-85de1593dfab(("patterns <br> 6d2e977b-3ae2-4abf <br> -8071-85de1593dfab"))--->|"<b> temporal_part_of"|2af35b4d-4c62-4d7d-942d-7c0f527f9a2c(("patterns <br> 2af35b4d-4c62-4d7d <br> -942d-7c0f527f9a2c"));
  6d2e977b-3ae2-4abf-8071-85de1593dfab(("patterns <br> 6d2e977b-3ae2-4abf <br> -8071-85de1593dfab"))--->|"data_EntityName"|Example_state_of_Lunar_Lander_Module_Eagle_LM-5["Example_state_of <br> _Lunar_Lander_Module_Eagle_LM-5"];
  6d2e977b-3ae2-4abf-8071-85de1593dfab(("patterns <br> 6d2e977b-3ae2-4abf <br> -8071-85de1593dfab"))--->|"type"|state_of_functional_system(["hqdm <br> state_of_functiona <br> l_system"]);
```
