``` mermaid
graph LR
  a5a6ba71-b2bb-4ed5-b079-e7cab5dac94f(("patterns <br> a5a6ba71-b2bb-4ed5 <br> -b079-e7cab5dac94f"))--->|"data_EntityName"|Example_individual_that_is_Lunar_Module_Eagle_LM-5["Example_individual <br> _that_is_Lunar_Module_Eagle_LM-5"];
  a5a6ba71-b2bb-4ed5-b079-e7cab5dac94f(("patterns <br> a5a6ba71-b2bb-4ed5 <br> -b079-e7cab5dac94f"))--->|"type"|functional_system(["hqdm <br> functional_system"]);
  e7b2866d-7667-4e3c-b829-1a23ae21f1c1(("patterns <br> e7b2866d-7667-4e3c <br> -b829-1a23ae21f1c1"))--->|"<b> temporal_part_of"|a5a6ba71-b2bb-4ed5-b079-e7cab5dac94f(("patterns <br> a5a6ba71-b2bb-4ed5 <br> -b079-e7cab5dac94f"));
  e7b2866d-7667-4e3c-b829-1a23ae21f1c1(("patterns <br> e7b2866d-7667-4e3c <br> -b829-1a23ae21f1c1"))--->|"data_EntityName"|Example_state_of_Lunar_Lander_Module_Eagle_LM-5["Example_state_of <br> _Lunar_Lander_Module_Eagle_LM-5"];
  e7b2866d-7667-4e3c-b829-1a23ae21f1c1(("patterns <br> e7b2866d-7667-4e3c <br> -b829-1a23ae21f1c1"))--->|"type"|state_of_functional_system(["hqdm <br> state_of_functiona <br> l_system"]);
```
